apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloto-tools-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reloto-tools
  template:
    metadata:
      labels:
        app: reloto-tools
    spec:
      containers:
        - name: reloto-tools
          image: conorburke/reloto-tools
          env:
            - name: RELOTO_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: reloto-jwt-secret
                  key: RELOTO_JWT_KEY
            - name: RELOTO_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: reloto-cookie-secret
                  key: RELOTO_COOKIE_SECRET
            - name: RELOTO_MONGO_URI_TOOLS
              valueFrom:
                secretKeyRef:
                  name: reloto-mongo-uri-tools
                  key: RELOTO_MONGO_URI_TOOLS
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: reloto
            #uses the pod name as the client id
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: reloto-tools-srv
spec:
  type: ClusterIP
  selector:
    app: reloto-tools
  ports:
    - name: reloto-tools
      protocol: TCP
      port: 3000
      targetPort: 3000