name: tests

on:
  pull_request
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
#      extract code out of project 
     - uses: actions/checkout@v2
     - run: cd tools && npm install && npm run test:ci