name: tests

on:
  pull_request:
    paths: 'payments/**'
  
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
#      extract code out of project 
     - uses: actions/checkout@v2
     - run: cd payments && npm install && npm run test:ci